#%RAML 1.0
title: Employee System API
version: v2.0
baseUri: http://localhost:8081/api

types:
  employee: !include dataTypes/Employees.raml
  errorResponse: !include dataTypes/ErrorResponse.raml
  successResponse: !include dataTypes/SuccessResponse.raml

traits: 
  employeeSearch: !include traits/trait-collection.raml

/employees:
  description: |
    Working with employees:
    * Retrieving all employees
    * Creating employees
  get:
    displayName: Get employees
    description: |
      Retrieve all the Employees according to the filtering.
    is: [ employeeSearch ]      
    responses:
      200:
        body:
          application/json:
            type: employee[]
            example: !include examples/get_employees_example.yaml
  post:
    displayName: Create employee
    description: |
      Create a new Employee
    body:
      application/json:
        type: employee
        example: !include examples/post_employees_example.yaml
    responses:
      201:
        description: Created
        body:
          application/json:
            type: employee
            example: |
                {
                  "id": "123456"
                }
                    
      422:
        description: Unprocessable entity
        body:
          application/json:
            type: errorResponse
            example: |
                {
                  "message": "Country is required."
                }
  /{id}:
    description: |
      Working with employees:
      * Retrieving specific employee
      * Updating specific employee
      * Deleting specific employee
    uriParameters:
      id:
        type: string | integer
        example: "301980"
        description: Represents the employee ID of native system
    get:
      displayName: Get employee by id
      description: Get Employee by ID
      responses:
        200:
          body:
            application/json:
              type: employee
              example: !include examples/get_employeeById_example.yaml
        404:
          body:
            application/json:
              type: errorResponse
              example: |
                {
                  "message": "Resource not found"
                }
    patch:
      displayName: Update employee by id
      description: Update Employee specified by ID
      body:
        application/json:
          type: employee
          example: !include examples/put_employee_example.yaml
      responses:
        200:
          body:
            application/json:
              type: successResponse
              example: |
                {
                  "status": "OK"
                }
        404:
          body:
            application/json:
              type: errorResponse
              example: |
                {
                  "message": "Resource not found"
                }
        422:
          description: Unprocessable entity
          body:
            application/json:
              type: errorResponse
              example: |
                {
                  "message": "You have to specify the whole adress, which consists of address line, city, country, region and postal code."
                }
    delete:
      displayName: Delete employee by id
      description: Delete Employee specified by ID
      responses:
        200:
          body:
            application/json:
              type: successResponse
              example: |
                {
                  "status": "OK"
                }
        404:
          body:
            application/json:
              type: errorResponse
              example: |
                {
                  "message": "Resource not found"
                }
